root_servers:
  a:
    operator: "Verisign (Formerly InterNIC)"
    ttl: 3600000
    ipv4: "198.41.0.4"
    ipv6: "2001:503:ba3e::2:30"

  b:
    operator: "USC-ISI"
    ttl: 3600000
    ipv4: "170.247.170.2"
    ipv6: "2801:1b8:10::b"

  c:
    operator: "Cogent Communications (Formerly PSI.NET)"
    ttl: 3600000
    ipv4: "192.33.4.12"
    ipv6: "2001:500:2::c"

  d:
    operator: "University of Maryland"
    ttl: 3600000
    ipv4: "199.7.91.13"
    ipv6: "2001:500:2d::d"

  e:
    operator: "NASA Ames Research Center"
    ttl: 3600000
    ipv4: "192.203.230.10"
    ipv6: "2001:500:a8::e"

  f:
    operator: "Internet Systems Consortium (ISC)"
    ttl: 3600000
    ipv4: "192.5.5.241"
    ipv6: "2001:500:2f::f"

  g:
    operator: "US DoD Network Information Center"
    ttl: 3600000
    ipv4: "192.112.36.4"
    ipv6: "2001:500:12::d0d"

  h:
    operator: "US Army Research Lab"
    ttl: 3600000
    ipv4: "198.97.190.53"
    ipv6: "2001:500:1::53"

  i:
    operator: "Netnod (Formerly NORDU.NET)"
    ttl: 3600000
    ipv4: "192.36.148.17"
    ipv6: "2001:7fe::53"

  j:
    operator: "Verisign, Inc."
    ttl: 3600000
    ipv4: "192.58.128.30"
    ipv6: "2001:503:c27::2:30"

  k:
    operator: "RIPE NCC"
    ttl: 3600000
    ipv4: "193.0.14.129"
    ipv6: "2001:7fd::1"

  l:
    operator: "ICANN"
    ttl: 3600000
    ipv4: "199.7.83.42"
    ipv6: "2001:500:9f::42"

  m:
    operator: "WIDE Project"
    ttl: 3600000
    ipv4: "202.12.27.33"
    ipv6: "2001:dc3::35"
